<?php

namespace App\Services;

use App\Models\Production\Production;
use App\Models\Supply\SupplierOrderItem;
use App\Models\Supply\SuppliesMovement;
use App\Models\Supply\Supply;
use App\Models\User;
use Illuminate\Support\Facades\DB;

/**
 * Handles stock entries and exits while keeping traceable movement logs.
 */
class InventoryMovementService
{
    /**
     * Moves a supplier order item into stock exactly once and records inbound movement.
     */
    public function receiveOrderItemIntoStock(SupplierOrderItem $item, string $orderRef, string $deliveryDate, ?User $user = null): Supply
    {
        return DB::transaction(function () use ($item, $orderRef, $deliveryDate, $user): Supply {
            /** @var SupplierOrderItem $lockedItem */
            $lockedItem = SupplierOrderItem::query()
                ->lockForUpdate()
                ->findOrFail($item->id);

            if ($lockedItem->isInSupplies() || $lockedItem->supply()->exists()) {
                throw new \RuntimeException('Supplier order item is already in stock.');
            }

            $totalQuantity = $this->resolveOrderItemStockQuantity($lockedItem);

            if ($totalQuantity <= 0) {
                throw new \InvalidArgumentException('Supplier order item quantity must be greater than zero.');
            }

            $batchNumber = $this->generateUniqueBatchNumber($lockedItem->batch_number);

            $supply = Supply::query()->create([
                'supplier_order_item_id' => $lockedItem->id,
                'supplier_listing_id' => $lockedItem->supplier_listing_id,
                'order_ref' => $orderRef,
                'batch_number' => $batchNumber,
                'unit_price' => $lockedItem->unit_price,
                'initial_quantity' => $totalQuantity,
                'quantity_in' => $totalQuantity,
                'quantity_out' => 0,
                'expiry_date' => $lockedItem->expiry_date,
                'delivery_date' => $deliveryDate,
                'is_in_stock' => true,
            ]);

            $this->recordInboundFromOrderItem($supply, $lockedItem, $user);

            $lockedItem->update([
                'is_in_supplies' => 'Stock',
                'moved_to_stock_at' => now(),
                'moved_to_stock_by' => $user?->id,
            ]);

            $lockedItem->supplierListing()->update([
                'price' => $lockedItem->unit_price,
            ]);

            $lockedItem->loadMissing('supplierListing.ingredient');

            $ingredient = $lockedItem->supplierListing?->ingredient;

            if ($ingredient && $lockedItem->unit_price !== null) {
                $ingredient->update([
                    'price' => $lockedItem->unit_price,
                ]);
            }

            return $supply;
        });
    }

    /**
     * Records an inbound movement generated by supplier reception.
     */
    public function recordInboundFromOrderItem(Supply $supply, SupplierOrderItem $item, ?User $user = null): SuppliesMovement
    {
        $quantity = $this->resolveOrderItemStockQuantity($item);
        $unit = $item->supplierListing?->unit_of_measure ?: 'kg';

        return SuppliesMovement::query()->create([
            'supply_id' => $supply->id,
            'supplier_order_item_id' => $item->id,
            'production_id' => null,
            'user_id' => $user?->id,
            'movement_type' => 'in',
            'quantity' => $quantity,
            'unit' => $unit,
            'reason' => 'Supplier order received into stock',
            'meta' => [
                'supplier_order_id' => $item->supplier_order_id,
                'order_ref' => $supply->order_ref,
                'batch_number' => $supply->batch_number,
            ],
            'moved_at' => now(),
        ]);
    }

    /**
     * Records an inbound movement generated by finished internal production.
     */
    public function recordInboundFromProduction(Supply $supply, Production $production, float $quantityKg, ?User $user = null, ?string $reason = null): SuppliesMovement
    {
        return SuppliesMovement::query()->create([
            'supply_id' => $supply->id,
            'supplier_order_item_id' => null,
            'production_id' => $production->id,
            'user_id' => $user?->id,
            'movement_type' => 'in',
            'quantity' => $quantityKg,
            'unit' => 'kg',
            'reason' => $reason ?? 'Production output moved to stock',
            'meta' => [
                'production_batch' => $production->getLotIdentifier(),
                'supply_batch' => $supply->batch_number,
                'source' => 'production_output',
            ],
            'moved_at' => now(),
        ]);
    }

    /**
     * Records an outbound movement when stock is consumed by production.
     */
    public function recordOutboundToProduction(Supply $supply, Production $production, float $quantityKg, ?User $user = null, ?string $reason = null): SuppliesMovement
    {
        return SuppliesMovement::query()->create([
            'supply_id' => $supply->id,
            'supplier_order_item_id' => $supply->supplier_order_item_id,
            'production_id' => $production->id,
            'user_id' => $user?->id,
            'movement_type' => 'out',
            'quantity' => $quantityKg,
            'unit' => $supply->supplierListing?->unit_of_measure ?: 'kg',
            'reason' => $reason ?? 'Allocated to production',
            'meta' => [
                'production_batch' => $production->getLotIdentifier(),
                'supply_batch' => $supply->batch_number,
            ],
            'moved_at' => now(),
        ]);
    }

    /**
     * Records a manual stock correction movement.
     */
    public function recordAdjustment(Supply $supply, float $quantityKg, string $reason, ?User $user = null): SuppliesMovement
    {
        return SuppliesMovement::query()->create([
            'supply_id' => $supply->id,
            'supplier_order_item_id' => $supply->supplier_order_item_id,
            'production_id' => null,
            'user_id' => $user?->id,
            'movement_type' => 'adjustment',
            'quantity' => $quantityKg,
            'unit' => $supply->supplierListing?->unit_of_measure ?: 'kg',
            'reason' => $reason,
            'meta' => [
                'supply_batch' => $supply->batch_number,
            ],
            'moved_at' => now(),
        ]);
    }

    /**
     * Records an allocation movement when stock is reserved for production.
     *
     * This creates an audit trail for reservations made via ProductionAllocationService.
     */
    public function recordAllocation(Supply $supply, Production $production, float $quantityKg, ?string $reason = null): SuppliesMovement
    {
        return SuppliesMovement::query()->create([
            'supply_id' => $supply->id,
            'supplier_order_item_id' => $supply->supplier_order_item_id,
            'production_id' => $production->id,
            'user_id' => null,
            'movement_type' => 'allocation',
            'quantity' => $quantityKg,
            'unit' => $supply->supplierListing?->unit_of_measure ?: 'kg',
            'reason' => $reason ?? 'Reserved for production',
            'meta' => [
                'production_batch' => $production->getLotIdentifier(),
                'supply_batch' => $supply->batch_number,
            ],
            'moved_at' => now(),
        ]);
    }

    /**
     * Records a release movement (negative allocation) when stock reservation is cancelled.
     *
     * This creates a compensating transaction instead of deleting the original allocation.
     */
    public function recordRelease(Supply $supply, Production $production, float $quantityKg, ?string $reason = null): SuppliesMovement
    {
        // Eager load supplierListing to prevent lazy loading violation
        $supply->loadMissing('supplierListing');

        return SuppliesMovement::query()->create([
            'supply_id' => $supply->id,
            'supplier_order_item_id' => $supply->supplier_order_item_id,
            'production_id' => $production->id,
            'user_id' => null,
            'movement_type' => 'allocation',
            'quantity' => -$quantityKg,
            'unit' => $supply->supplierListing?->unit_of_measure ?: 'kg',
            'reason' => $reason ?? 'Released from production',
            'meta' => [
                'production_batch' => $production->getLotIdentifier(),
                'supply_batch' => $supply->batch_number,
            ],
            'moved_at' => now(),
        ]);
    }

    /**
     * @deprecated Use recordRelease() instead to create compensating transactions
     */
    public function deleteAllocationsForProductionItem(Production $production, Supply $supply, float $quantity): void
    {
        // Create compensating negative movement instead of deleting
        $this->recordRelease($supply, $production, $quantity);
    }

    /**
     * Deletes all allocation movements for a production.
     *
     * Used when cancelling productions.
     */
    public function deleteAllAllocationsForProduction(Production $production): void
    {
        SuppliesMovement::query()
            ->where('production_id', $production->id)
            ->where('movement_type', 'allocation')
            ->delete();
    }

    private function resolveOrderItemStockQuantity(SupplierOrderItem $item): float
    {
        $quantity = (float) ($item->quantity ?? 0);
        $unitWeight = (float) ($item->unit_weight ?? 0);
        $unitMultiplier = $unitWeight > 0 ? $unitWeight : 1;

        return round($quantity * $unitMultiplier, 3);
    }

    /**
     * Generate a unique batch number by appending a sequential suffix if the original already exists.
     *
     * For example, if "ABC123" exists, returns "ABC123-1". If "ABC123-1" also exists, returns "ABC123-2", etc.
     */
    private function generateUniqueBatchNumber(?string $originalBatchNumber): string
    {
        if (empty($originalBatchNumber)) {
            return 'NO-BATCH-'.now()->format('YmdHis');
        }

        // Check if the original batch number exists
        if (! Supply::query()->where('batch_number', $originalBatchNumber)->exists()) {
            return $originalBatchNumber;
        }

        // Find the next available suffix
        $counter = 1;
        $baseBatchNumber = $originalBatchNumber;

        // Check if the original already has a suffix pattern and extract the base
        if (preg_match('/^(.+)-(\d+)$/', $originalBatchNumber, $matches)) {
            $baseBatchNumber = $matches[1];
            $counter = (int) $matches[2] + 1;
        }

        // Find the next available suffix
        while (Supply::query()->where('batch_number', $baseBatchNumber.'-'.$counter)->exists()) {
            $counter++;
        }

        return $baseBatchNumber.'-'.$counter;
    }
}
